DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE `CUSTOMER`(
   ID   INT  PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS CHAR (25) ,
   SALARY DECIMAL (18, 2)
);

DROP TABLE IF EXISTS `USER_AUTHORITY`;
CREATE TABLE `USER_AUTHORITY`(
   `AUTHORITY_ID`  INT,
   `USER_ID`   INT
);

DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS`(
    `ID`   INT  PRIMARY KEY AUTO_INCREMENT,
    `USERNAME` VARCHAR (250) NOT NULL,
    `PASSWORD` VARCHAR (250) NOT NULL,
    `DATE_CREATED` TIMESTAMP DEFAULT (sysdate)
);

DROP TABLE IF EXISTS `AUTHORITY`;
CREATE TABLE `AUTHORITY`(
    `ID`   INT  PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(100)
);
